### ISSUE TITLE
How to get rid of old groups

### ISSUE THREAD

**Issue by totalgee** [bgola/tcposcrouter#1]
Hi there, I was wondering if there is a way to "cleanup" old Groups, or do you need to restart the tcposcrouter server? Just wondering if there is a message we can send to a Group to remove itself, or perhaps remove any Groups that don't have active connections?

**Comment by bgola** [comment]
thanks for the report @totalgee 

that is a bug, expected behavior is that the group is removed after there are no more connections to it.

fixed in https://github.com/bgola/tcposcrouter/commit/911622da220e879585d07e6c9e0217d24a89f28f

**Comment by totalgee** [comment]
Thanks!
