### ISSUE TITLE
Using tcposcrouter with Max MSP

### ISSUE THREAD

**Issue by jtragtenberg** [bgola/tcposcrouter#2]
Hello Bruno,
I did your workshop at the Network Music Festival and now I finally got the time to try to implement your library to Max/MSP.
I remember you mentioned that the join message was /oscrouter/register, userName, passwrod, group, groupPassword but what is the port the tcposcrouter server is listening at? And in the tcp receive should I listen to what port for the reply? Are the two way communications over the same port?

Could you tell me what are the key messages I can use to debug, like what is the .group message to check who is in a certain group?

I'm first trying to use the jit.net.sens and jit.net.recv objects in max, but they are used to send and receive matrices from jitter. But I believe it could also send messages. What would be a good set of messages to send and expect to receive back?

Thank you very much, and congratulations for the amazing solution with no need for public IPs...

**Comment by bgola** [comment]
Hi @jtragtenberg sorry for taking so long to reply I only saw your question here now.

I just added some examples for setting up tcposcrouter with PureData and I guess it could be helpful for MAX/MSP as well?
