### ISSUE TITLE
[Q] how to solve this?

### ISSUE THREAD

**Issue by paum3** [bgola/tcposcrouter#4]
Hi,

it was not easy to find a proper title for this question.
What I would like  to achieve: I have an Android app oschooks which can send OSC sensor data from my phone to network (which actually works over local network out of a box).
From oschooks mobile app I can send data to whatever IP and port but I can't figure out (or better it could take days..) how to use osctcprouter to resend incoming data from my mobile to SC running on other laptop over internet.

Thank you for any suggestion.
paum

**Comment by bgola** [comment]
Hi!
I guess oschooks sends it via UDP.. you would need to receive this UDP message and then send it to tcposcrouter from another process.
